In [22]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


reviews = ['nice food',
          'amazing restaurant',
          'too good',
          'just loved it!',
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'poor quality',
          'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [23]:
one_hot('amazing restaurant',30) # we can choose the number within which we need to choose # 21 is of amazing and 28 is of restaurant. 

[5, 5]

In [24]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]

In [25]:
max_length = 4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[24 23  0  0]
 [ 5  5  0  0]
 [ 3  8  0  0]
 [17  8 13  0]
 [13 26 15  0]
 [ 9 23  0  0]
 [16 26 27  0]
 [21 24  0  0]
 [21 13  0  0]
 [25 11  0  0]]


In [26]:
embedded_vector_size=5

model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [27]:
x=padded_reviews
y=sentiment

In [28]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_3 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [29]:
model.fit(x,y,epochs=50,verbose=0) # verbose is used to not show output on console.

In [30]:
# evaluate the model
loss,accuracy=model.evaluate(x,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step - accuracy: 1.0000 - loss: 0.5957


1.0

In [34]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [32]:
weights[13]

array([-0.05649968,  0.07691912, -0.05849699,  0.00849807, -0.01271859],
      dtype=float32)

In [33]:
weights[16]

array([ 0.07616841, -0.00147721, -0.07890356, -0.04348492, -0.07478122],
      dtype=float32)